# Generated by Django 5.1 on 2024-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_donation_amount_alter_post_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='collected',
            field=models.IntegerField(default=0),
        ),
    ]
