# Generated by Django 5.1 on 2024-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='balance_after_donation',
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
