# Generated by Django 5.1 on 2024-11-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_delete_withdraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposite',
        ),
    ]
